package com.vpr.screenlate.dictionary.engine.hoshidicts

import android.content.res.Resources
import androidx.annotation.StringRes
import com.vpr.screenlate.dictionary.api.model.Transform

/**
 * Localized names and descriptions of hoshidicts' Japanese inflection rules, keyed by the rule name the engine
 * reports. Names written in kana stay as they are; the name itself stays in [Transform.name] for Anki's
 * `{conjugation}`. Generated by tools/generate_inflections.py.
 */
internal object JapaneseInflections {
    private class Strings(@param:StringRes val label: Int?, @param:StringRes val description: Int?)

    private val STRINGS: Map<String, Strings> = mapOf(
        "-ば" to Strings(null, R.string.inflection_ja_ba),
        "-ゃ" to Strings(null, R.string.inflection_ja_ya),
        "-ちゃ" to Strings(null, R.string.inflection_ja_cha),
        "-ちゃう" to Strings(null, R.string.inflection_ja_chau),
        "-ちまう" to Strings(null, R.string.inflection_ja_chimau),
        "-しまう" to Strings(null, R.string.inflection_ja_shimau),
        "-なさい" to Strings(null, R.string.inflection_ja_nasai),
        "-そう" to Strings(null, R.string.inflection_ja_sou),
        "-すぎる" to Strings(null, R.string.inflection_ja_sugiru),
        "-過ぎる" to Strings(null, R.string.inflection_ja_sugigiru_kanji),
        "-たい" to Strings(null, R.string.inflection_ja_tai),
        "-たら" to Strings(null, R.string.inflection_ja_tara),
        "-たり" to Strings(null, R.string.inflection_ja_tari),
        "-て" to Strings(null, R.string.inflection_ja_te),
        "-ず" to Strings(null, R.string.inflection_ja_zu),
        "-ぬ" to Strings(null, R.string.inflection_ja_nu),
        "-ん" to Strings(null, R.string.inflection_ja_n),
        "-んばかり" to Strings(null, R.string.inflection_ja_nbakari),
        "-んとする" to Strings(null, R.string.inflection_ja_ntosuru),
        "-む" to Strings(null, R.string.inflection_ja_mu),
        "-ざる" to Strings(null, R.string.inflection_ja_zaru),
        "-ねば" to Strings(null, R.string.inflection_ja_neba),
        "-く" to Strings(null, R.string.inflection_ja_ku),
        "causative" to Strings(R.string.inflection_ja_causative_label, R.string.inflection_ja_causative),
        "short causative" to Strings(R.string.inflection_ja_short_causative_label, R.string.inflection_ja_short_causative),
        "imperative" to Strings(R.string.inflection_ja_imperative_label, R.string.inflection_ja_imperative),
        "continuative" to Strings(R.string.inflection_ja_continuative_label, R.string.inflection_ja_continuative),
        "negative" to Strings(R.string.inflection_ja_negative_label, R.string.inflection_ja_negative),
        "-さ" to Strings(null, R.string.inflection_ja_sa),
        "passive" to Strings(R.string.inflection_ja_passive_label, R.string.inflection_ja_passive),
        "-た" to Strings(null, R.string.inflection_ja_ta),
        "-ます" to Strings(null, R.string.inflection_ja_masu),
        "potential" to Strings(R.string.inflection_ja_potential_label, R.string.inflection_ja_potential),
        "potential or passive" to Strings(R.string.inflection_ja_potential_or_passive_label, R.string.inflection_ja_potential_or_passive),
        "volitional" to Strings(R.string.inflection_ja_volitional_label, R.string.inflection_ja_volitional),
        "volitional slang" to Strings(R.string.inflection_ja_volitional_slang_label, R.string.inflection_ja_volitional_slang),
        "-まい" to Strings(null, R.string.inflection_ja_mai),
        "-おく" to Strings(null, R.string.inflection_ja_oku),
        "-いる" to Strings(null, R.string.inflection_ja_iru),
        "-き" to Strings(null, R.string.inflection_ja_ki),
        "-げ" to Strings(null, R.string.inflection_ja_ge),
        "-がる" to Strings(null, R.string.inflection_ja_garu),
        "-え" to Strings(null, R.string.inflection_ja_e),
        "n-slang" to Strings(R.string.inflection_ja_n_slang_label, null),
        "imperative negative slang" to Strings(R.string.inflection_ja_imperative_negative_slang_label, null),
        "kansai-ben negative" to Strings(R.string.inflection_ja_kansai_ben_negative_label, R.string.inflection_ja_kansai_ben_negative),
        "kansai-ben -て" to Strings(R.string.inflection_ja_kansai_ben_te_label, R.string.inflection_ja_kansai_ben_te),
        "kansai-ben -た" to Strings(R.string.inflection_ja_kansai_ben_ta_label, R.string.inflection_ja_kansai_ben_ta),
        "kansai-ben -たら" to Strings(R.string.inflection_ja_kansai_ben_tara_label, R.string.inflection_ja_kansai_ben_tara),
        "kansai-ben -たり" to Strings(R.string.inflection_ja_kansai_ben_tari_label, R.string.inflection_ja_kansai_ben_tari),
        "kansai-ben -く" to Strings(R.string.inflection_ja_kansai_ben_ku_label, R.string.inflection_ja_kansai_ben_ku),
        "kansai-ben adjective -て" to Strings(R.string.inflection_ja_kansai_ben_adjective_te_label, R.string.inflection_ja_kansai_ben_adjective_te),
        "kansai-ben adjective negative" to Strings(R.string.inflection_ja_kansai_ben_adjective_negative_label, R.string.inflection_ja_kansai_ben_adjective_negative),
        "-ましゅ" to Strings(null, R.string.inflection_ja_mashu),
        "-ください" to Strings(null, R.string.inflection_ja_kudasai),
        "-くださる" to Strings(null, R.string.inflection_ja_kudasaru),
        "-ごらん" to Strings(null, R.string.inflection_ja_goran),
        "-ごらんなさい" to Strings(null, R.string.inflection_ja_gorannasai),
        "-いただく" to Strings(null, R.string.inflection_ja_itadaku),
        "-あげる" to Strings(null, R.string.inflection_ja_ageru),
        "-くれる" to Strings(null, R.string.inflection_ja_kureru),
        "-もらう" to Strings(null, R.string.inflection_ja_morau),
        "-やる" to Strings(null, R.string.inflection_ja_yaru),
        "-さしあげる" to Strings(null, R.string.inflection_ja_sashiageru),
        "-みる" to Strings(null, R.string.inflection_ja_miru),
        "-みせる" to Strings(null, R.string.inflection_ja_miseru),
        "-ある" to Strings(null, R.string.inflection_ja_aru),
        "-いく" to Strings(null, R.string.inflection_ja_iku),
        "-くる" to Strings(null, R.string.inflection_ja_kuru),
        "-なさそう" to Strings(null, R.string.inflection_ja_nasasou),
        "-ながら" to Strings(null, R.string.inflection_ja_nagara),
        "-やがる" to Strings(null, R.string.inflection_ja_yagaru),
    )

    /** Every rule name the map knows, for checking it against the engine source. */
    val names: Set<String> get() = STRINGS.keys

    /** [transform] with the label and description in the resources' language; unknown rules keep the engine's text. */
    fun localize(resources: Resources, transform: Transform): Transform {
        val strings = STRINGS[transform.name] ?: return transform
        return transform.copy(
            label = strings.label?.let(resources::getString) ?: transform.label,
            description = strings.description?.let(resources::getString) ?: transform.description,
        )
    }
}
