package com.vpr.screenlate.dictionary.engine.hoshidicts

import android.content.res.Resources
import androidx.annotation.StringRes
import com.vpr.screenlate.dictionary.api.model.Transform

/**
 * Localized names and descriptions of the inflection rules of languages looked up through Yomitan's language code, by
 * language code and rule id (what the engine reports). Affixes and names in the language's own script stay as they
 * are; the id stays in [Transform.name] for Anki's `{conjugation}`. Generated by
 * scripts/yomitan-language/generate-inflections.mjs.
 */
internal object YomitanInflections {
    private class Strings(@param:StringRes val label: Int?, @param:StringRes val description: Int?)

    private val STRINGS: Map<String, Map<String, Strings>> = mapOf(
        "en" to mapOf(
            "plural" to Strings(R.string.inflection_en_plural_label, R.string.inflection_en_plural),
            "possessive" to Strings(R.string.inflection_en_possessive_label, R.string.inflection_en_possessive),
            "past" to Strings(R.string.inflection_en_past_label, R.string.inflection_en_past),
            "ing" to Strings(R.string.inflection_en_ing_label, R.string.inflection_en_ing),
            "3rd pers. sing. pres" to Strings(R.string.inflection_en_3rd_pers_sing_pres_label, R.string.inflection_en_3rd_pers_sing_pres),
            "interposed object" to Strings(R.string.inflection_en_interposed_object_label, R.string.inflection_en_interposed_object),
            "archaic" to Strings(R.string.inflection_en_archaic_label, R.string.inflection_en_archaic),
            "adverb" to Strings(R.string.inflection_en_adverb_label, R.string.inflection_en_adverb),
            "comparative" to Strings(R.string.inflection_en_comparative_label, R.string.inflection_en_comparative),
            "superlative" to Strings(R.string.inflection_en_superlative_label, R.string.inflection_en_superlative),
            "dropped g" to Strings(R.string.inflection_en_dropped_g_label, R.string.inflection_en_dropped_g),
            "-y" to Strings(null, R.string.inflection_en_y),
            "un-" to Strings(null, R.string.inflection_en_un),
            "going-to future" to Strings(R.string.inflection_en_going_to_future_label, R.string.inflection_en_going_to_future),
            "will future" to Strings(R.string.inflection_en_will_future_label, R.string.inflection_en_will_future),
            "imperative negative" to Strings(R.string.inflection_en_imperative_negative_label, R.string.inflection_en_imperative_negative),
            "-able" to Strings(null, R.string.inflection_en_able),
        ),
    )

    /** Rule ids of [language] (ISO 639-1); empty for a language without rules. */
    fun names(language: String): Set<String> = STRINGS[language]?.keys.orEmpty()

    /** [transform] with its label and description in the resources' language; null when [language] has no such rule. */
    fun localize(resources: Resources, language: String, transform: Transform): Transform? {
        val strings = STRINGS[language]?.get(transform.name) ?: return null
        return transform.copy(
            label = strings.label?.let(resources::getString) ?: transform.label,
            description = strings.description?.let(resources::getString) ?: transform.description,
        )
    }
}
