"""Regenerates the Japanese inflection strings from hoshidicts' deinflector.cpp.

Writes res/values/inflections_ja.xml (rule names in Latin letters and English descriptions, as the engine has them)
and JapaneseInflections.kt (rule name to string resources), then lists the keys that translations in
res/values-*/inflections_ja.xml lack or no longer need. Translations are edited by hand.

Usage, from the repository root: python dictionary/engine-hoshidicts/tools/generate_inflections.py
"""
import glob
import os
import re

MODULE = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
SOURCE = os.path.join(MODULE, 'src/main/cpp/hoshidicts/src/deinflector.cpp')
RES = os.path.join(MODULE, 'src/main/res')
KOTLIN = os.path.join(MODULE, 'src/main/java/com/vpr/screenlate/dictionary/engine/hoshidicts/JapaneseInflections.kt')

STR = r'"((?:\\.|[^"\\])*)"'

KANA = {
    'あ': 'a', 'い': 'i', 'う': 'u', 'え': 'e', 'お': 'o',
    'か': 'ka', 'き': 'ki', 'く': 'ku', 'け': 'ke', 'こ': 'ko',
    'が': 'ga', 'ぎ': 'gi', 'ぐ': 'gu', 'げ': 'ge', 'ご': 'go',
    'さ': 'sa', 'し': 'shi', 'す': 'su', 'せ': 'se', 'そ': 'so',
    'ざ': 'za', 'じ': 'ji', 'ず': 'zu', 'ぜ': 'ze', 'ぞ': 'zo',
    'た': 'ta', 'ち': 'chi', 'つ': 'tsu', 'て': 'te', 'と': 'to',
    'だ': 'da', 'で': 'de', 'ど': 'do',
    'な': 'na', 'に': 'ni', 'ぬ': 'nu', 'ね': 'ne', 'の': 'no',
    'は': 'ha', 'ひ': 'hi', 'ふ': 'fu', 'へ': 'he', 'ほ': 'ho',
    'ば': 'ba', 'び': 'bi', 'ぶ': 'bu', 'べ': 'be', 'ぼ': 'bo',
    'ま': 'ma', 'み': 'mi', 'む': 'mu', 'め': 'me', 'も': 'mo',
    'や': 'ya', 'ゆ': 'yu', 'よ': 'yo',
    'ら': 'ra', 'り': 'ri', 'る': 'ru', 'れ': 're', 'ろ': 'ro',
    'わ': 'wa', 'を': 'wo', 'ん': 'n',
}
SMALL = {'ゃ': 'a', 'ゅ': 'u', 'ょ': 'o'}


def unescape(s):
    out, i = [], 0
    while i < len(s):
        c = s[i]
        if c == '\\' and i + 1 < len(s):
            out.append({'n': '\n', 't': '\t'}.get(s[i + 1], s[i + 1]))
            i += 2
        else:
            out.append(c)
            i += 1
    return ''.join(out)


def rules():
    """(name, English description) of every add_group() call, with the shared description constants expanded."""
    src = open(SOURCE, encoding='utf-8').read()
    consts = {}
    for m in re.finditer(r'constexpr std::string_view (\w+) =\s*((?:' + STR + r'\s*)+);', src):
        consts[m.group(1)] = ''.join(unescape(x) for x in re.findall(STR, m.group(2)))
    found = []
    for m in re.finditer(r'add_group\(\s*\{(.*?)\}\s*\)', src, re.S):
        body = m.group(1)
        name = unescape(re.search(r'\.name = ' + STR, body).group(1))
        description = ''
        d = re.search(r'\.description =(.*)$', body, re.S)
        if d:
            for token in re.finditer(STR + r'|std::string\((\w+)\)|\b(\w+)\b', d.group(1)):
                if token.group(1) is not None:
                    description += unescape(token.group(1))
                elif token.group(2):
                    description += consts[token.group(2)]
                elif token.group(3) in consts:
                    description += consts[token.group(3)]
        found.append((name, description.strip()))
    return found


def romaji(text):
    out = ''
    for c in text:
        if c in SMALL:
            base = out[:-1] if out.endswith('i') else out
            out = (base if base.endswith(('sh', 'ch', 'j')) else base + 'y') + SMALL[c]
        elif c == '過':
            out += 'sugi'
        else:
            out += KANA.get(c, c)
    return out


def key(name):
    k = re.sub(r'[^a-z0-9]+', '_', romaji(name).lower()).strip('_')
    return 'inflection_ja_' + k + ('_kanji' if '過' in name else '')


def has_label(name):
    return re.search(r'[a-z]', name) is not None


def xml(text):
    text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    return text.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"').replace('\n', '\\n')


def main():
    found = rules()
    keys = [key(name) for name, _ in found]
    assert len(set(keys)) == len(keys), 'two rules share a resource key'

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Japanese inflections: rule names and descriptions from Yomitan\'s japanese-transforms.js through '
        'hoshidicts (GPL-3.0). Generated by tools/generate_inflections.py; do not edit. -->',
        '<resources>',
    ]
    expected = set()
    for (name, description), k in zip(found, keys):
        lines.append(f'    <!-- {name} -->')
        if has_label(name):
            lines.append(f'    <string name="{k}_label">{xml(name)}</string>')
            expected.add(k + '_label')
        if description:
            lines.append(f'    <string name="{k}">{xml(description)}</string>')
            expected.add(k)
    lines.append('</resources>')
    with open(os.path.join(RES, 'values/inflections_ja.xml'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')

    rows = []
    for (name, description), k in zip(found, keys):
        label = f'R.string.{k}_label' if has_label(name) else 'null'
        text = f'R.string.{k}' if description else 'null'
        rows.append(f'        "{name}" to Strings({label}, {text}),')
    rows_text = '\n'.join(rows)
    kotlin = f'''package com.vpr.screenlate.dictionary.engine.hoshidicts

import android.content.res.Resources
import androidx.annotation.StringRes
import com.vpr.screenlate.dictionary.api.model.Transform

/**
 * Localized names and descriptions of hoshidicts' Japanese inflection rules, keyed by the rule name the engine
 * reports. Names written in kana stay as they are; the name itself stays in [Transform.name] for Anki's
 * `{{conjugation}}`. Generated by tools/generate_inflections.py.
 */
internal object JapaneseInflections {{
    private class Strings(@param:StringRes val label: Int?, @param:StringRes val description: Int?)

    private val STRINGS: Map<String, Strings> = mapOf(
{rows_text}
    )

    /** Every rule name the map knows, for checking it against the engine source. */
    val names: Set<String> get() = STRINGS.keys

    /** [transform] with the label and description in the resources' language; unknown rules keep the engine's text. */
    fun localize(resources: Resources, transform: Transform): Transform {{
        val strings = STRINGS[transform.name] ?: return transform
        return transform.copy(
            label = strings.label?.let(resources::getString) ?: transform.label,
            description = strings.description?.let(resources::getString) ?: transform.description,
        )
    }}
}}
'''
    with open(KOTLIN, 'w', encoding='utf-8', newline='\n') as f:
        f.write(kotlin)
    print(f'{len(found)} rules')

    for path in sorted(glob.glob(os.path.join(RES, 'values-*/inflections_ja.xml'))):
        present = set(re.findall(r'<string name="([^"]+)"', open(path, encoding='utf-8').read()))
        missing, stale = sorted(expected - present), sorted(present - expected)
        if missing or stale:
            print(f'{os.path.relpath(path, MODULE)}: missing {missing}, no longer needed {stale}')


if __name__ == '__main__':
    main()
