"""Writes the table of translation languages (core/translate/.../TranslationLanguageTable.kt).

Reads the languages Microsoft's translator (Bing, Edge) and Google's gtx endpoint translate into, joins them under one
BCP 47 tag each and prints the Kotlin file. Run from the repository root:

    python scripts/translation/languages.py > core/translate/src/main/java/com/vpr/screenlate/core/translate/TranslationLanguageTable.kt

With two arguments it reads saved answers of the two lists instead: languages.py microsoft.json google.json
"""
import json
import sys
import urllib.request

MICROSOFT_URL = "https://api.cognitive.microsofttranslator.com/languages?api-version=3.0&scope=translation"
GOOGLE_URL = "https://translate.googleapis.com/translate_a/l?client=gtx&hl=en"

# Codes that name a language differently from its BCP 47 tag.
MICROSOFT_TAGS = {"mn-Cyrl": "mn", "nya": "ny", "lug": "lg", "run": "rn", "ku": "ckb", "pt": "pt-BR"}
GOOGLE_TAGS = {
    "zh-CN": "zh-Hans", "zh-TW": "zh-Hant", "iw": "he", "tl": "fil", "no": "nb", "jw": "jv", "mni-Mtei": "mni",
    "sr": "sr-Cyrl", "fa-AF": "prs", "ku": "kmr", "pt": "pt-BR",
}


def load(path, url):
    if path:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    with urllib.request.urlopen(url, timeout=20) as response:
        return json.loads(response.read().decode("utf-8"))


def main():
    paths = sys.argv[1:3] if len(sys.argv) >= 3 else [None, None]
    microsoft = load(paths[0], MICROSOFT_URL)["translation"]
    google = load(paths[1], GOOGLE_URL)["tl"]
    languages = {}
    for code, info in microsoft.items():
        tag = MICROSOFT_TAGS.get(code, code)
        languages.setdefault(tag, {})["microsoft"] = code
        languages[tag]["name"] = info["name"]
    for code, name in google.items():
        tag = GOOGLE_TAGS.get(code, code)
        languages.setdefault(tag, {})["google"] = code
        languages[tag].setdefault("name", name)
    languages["pt-BR"]["name"] = "Portuguese (Brazil)"

    def quoted(value):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"' if value is not None else "null"

    out = sys.stdout
    out.reconfigure(encoding="utf-8", newline="\n")
    out.write("package com.vpr.screenlate.core.translate\n\n")
    out.write("// Generated by scripts/translation/languages.py from the services' language lists; do not edit.\n\n")
    out.write("/** Tag, English name, Microsoft code (Bing, Edge), Google code. */\n")
    out.write("internal val TRANSLATION_LANGUAGES: List<TranslationLanguage> = listOf(\n")
    for tag in sorted(languages, key=str.lower):
        entry = languages[tag]
        out.write(
            f"    TranslationLanguage({quoted(tag)}, {quoted(entry['name'])}, "
            f"{quoted(entry.get('microsoft'))}, {quoted(entry.get('google'))}),\n"
        )
    out.write(")\n")


if __name__ == "__main__":
    main()
